apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umbrella
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/OpenGuidou/argocd-sso-reprod.git'
      targetRevision: HEAD
      path: '.'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true