apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: extra-rb-argocd
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd
  - kind: ServiceAccount
    name: argocd-server
    namespace: argocd
roleRef:
  kind: Role
  name: extra-rights-argocd
  apiGroup: rbac.authorization.k8s.io