apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/OpenGuidou/argocd-sso-reprod.git'
      targetRevision: HEAD
      ref: git-repo
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.6.8
      helm:
        valueFiles: 
          - $git-repo/argo-cd/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true